// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_60secmultipleo = "CgkI4ub4wrMNEAIQCA"; // <GPGSID>
        public const string leaderboard_60secmultiplex = "CgkI4ub4wrMNEAIQBA"; // <GPGSID>
        public const string achievement_45_touchs = "CgkI4ub4wrMNEAIQDA"; // <GPGSID>
        public const string achievement_10_touchs = "CgkI4ub4wrMNEAIQCQ"; // <GPGSID>
        public const string achievement_15_touchs = "CgkI4ub4wrMNEAIQCg"; // <GPGSID>
        public const string achievement = "CgkI4ub4wrMNEAIQCw"; // <GPGSID>
        public const string leaderboard_30secmultipleo = "CgkI4ub4wrMNEAIQBw"; // <GPGSID>
        public const string leaderboard_20secmultiplex = "CgkI4ub4wrMNEAIQAg"; // <GPGSID>
        public const string leaderboard_20secmultipleo = "CgkI4ub4wrMNEAIQBg"; // <GPGSID>
        public const string leaderboard_10secmultiplex = "CgkI4ub4wrMNEAIQAQ"; // <GPGSID>
        public const string leaderboard_10secmultipleo = "CgkI4ub4wrMNEAIQBQ"; // <GPGSID>
        public const string leaderboard_30secmultiplex = "CgkI4ub4wrMNEAIQAw"; // <GPGSID>

}

